export interface TerminalPalette {
  background: string;
  foreground: string;
  cursor: string;
  selectionBackground?: string;
  black: string;
  red: string;
  green: string;
  yellow: string;
  blue: string;
  magenta: string;
  cyan: string;
  white: string;
  brightBlack: string;
  brightRed: string;
  brightGreen: string;
  brightYellow: string;
  brightBlue: string;
  brightMagenta: string;
  brightCyan: string;
  brightWhite: string;
}

export interface ThemeDef {
  id: string;
  label: string;
  mode: "dark" | "light";
  /** 4 dots shown in the picker: bg, then 3 representative accent hues. */
  swatch: [string, string, string, string];
  vars: Record<string, string>;
  /** xterm.js needs its own explicit palette — it renders to canvas, so CSS
   * custom properties never reach it. */
  terminal: TerminalPalette;
}

export const THEMES: ThemeDef[] = [
  // The palette theme.css itself bakes into :root (light) and
  // :root[data-theme="dark"] — "metaharn" (橙), the project's own namesake
  // accent — existed only as a brief pre-JS flash before SettingsContext's
  // effect overwrote document.documentElement.style with one of the
  // borrowed palettes below on every mount; it had no id here and so no
  // path to ever actually be chosen. Values copied directly from theme.css
  // (not re-derived) to guarantee they match exactly; xterm needs its own
  // full ANSI palette that theme.css never defined at all, composed to fit
  // the same warm accent rather than reusing another theme's hues verbatim.
  {
    id: "metaharn-dark",
    label: "MetaHarn Dark",
    mode: "dark",
    swatch: ["#17140f", "#f2823f", "#9ec97a", "#7aa2c7"],
    vars: {
      "--color-bg": "#17140f",
      "--color-bg-secondary": "#1e1911",
      "--color-bg-elevated": "#241e15",
      "--color-bg-hover": "#2b2417",
      "--color-border": "#382e1e",
      "--color-text": "#f2ece2",
      "--color-text-secondary": "#b7ac98",
      "--color-text-muted": "#7d7261",
      "--color-accent": "#f2823f",
      "--color-accent-hover": "#f6975c",
      "--color-accent-soft": "#362317",
      "--color-user-bubble": "#f2ece2",
      "--color-user-bubble-text": "#17140f",
      "--color-tool-bubble": "#241e15",
      "--color-error": "#e08574",
      "--color-error-soft": "#362017",
      "--color-editor-bg": "#1e1911",
    },
    terminal: {
      background: "#17140f",
      foreground: "#f2ece2",
      cursor: "#f2823f",
      selectionBackground: "#382e1e",
      black: "#241e15",
      red: "#e08574",
      green: "#9ec97a",
      yellow: "#e0af68",
      blue: "#7aa2c7",
      magenta: "#c99bd6",
      cyan: "#7fc7c0",
      white: "#b7ac98",
      brightBlack: "#7d7261",
      brightRed: "#f2a394",
      brightGreen: "#b8dc96",
      brightYellow: "#f6c987",
      brightBlue: "#97bcd9",
      brightMagenta: "#ddb8e8",
      brightCyan: "#a0ddd6",
      brightWhite: "#f2ece2",
    },
  },
  {
    id: "metaharn-light",
    label: "MetaHarn Light",
    mode: "light",
    swatch: ["#ffffff", "#e0630f", "#6b8e3d", "#3d6f96"],
    vars: {
      "--color-bg": "#ffffff",
      "--color-bg-secondary": "#f7f6f3",
      "--color-bg-elevated": "#ffffff",
      "--color-bg-hover": "#f0ede7",
      "--color-border": "#e6e1d8",
      "--color-text": "#1c1712",
      "--color-text-secondary": "#6b6259",
      "--color-text-muted": "#a39a8c",
      "--color-accent": "#e0630f",
      "--color-accent-hover": "#c8560c",
      "--color-accent-soft": "#fdf0e4",
      "--color-user-bubble": "#1c1712",
      "--color-user-bubble-text": "#ffffff",
      "--color-tool-bubble": "#f0ede7",
      "--color-error": "#b3402f",
      "--color-error-soft": "#fbeae7",
      "--color-editor-bg": "#ffffff",
    },
    terminal: {
      background: "#ffffff",
      foreground: "#1c1712",
      cursor: "#e0630f",
      selectionBackground: "#e6e1d8",
      black: "#1c1712",
      red: "#b3402f",
      green: "#6b8e3d",
      yellow: "#a67c1f",
      blue: "#3d6f96",
      magenta: "#96518f",
      cyan: "#3d8f88",
      white: "#6b6259",
      brightBlack: "#a39a8c",
      brightRed: "#c8560c",
      brightGreen: "#85ad5c",
      brightYellow: "#c99a2f",
      brightBlue: "#5a8caf",
      brightMagenta: "#b06fa8",
      brightCyan: "#5aada5",
      brightWhite: "#1c1712",
    },
  },
  {
    id: "tokyo-night-storm",
    label: "Tokyo Night Storm",
    mode: "dark",
    swatch: ["#24283b", "#7aa2f7", "#9ece6a", "#bb9af7"],
    vars: {
      "--color-bg": "#24283b",
      "--color-bg-secondary": "#1f2335",
      "--color-bg-elevated": "#292e42",
      "--color-bg-hover": "#2f334d",
      "--color-border": "#3b4261",
      "--color-text": "#c0caf5",
      "--color-text-secondary": "#a9b1d6",
      "--color-text-muted": "#565f89",
      "--color-accent": "#7aa2f7",
      "--color-accent-hover": "#89b4fa",
      "--color-accent-soft": "#2a3457",
      "--color-user-bubble": "#c0caf5",
      "--color-user-bubble-text": "#1a1b26",
      "--color-tool-bubble": "#292e42",
      "--color-error": "#f7768e",
      "--color-error-soft": "#3a2734",
      "--color-editor-bg": "#1f2335",
    },
    terminal: {
      background: "#24283b",
      foreground: "#c0caf5",
      cursor: "#7aa2f7",
      selectionBackground: "#364a82",
      black: "#414868",
      red: "#f7768e",
      green: "#9ece6a",
      yellow: "#e0af68",
      blue: "#7aa2f7",
      magenta: "#bb9af7",
      cyan: "#7dcfff",
      white: "#a9b1d6",
      brightBlack: "#414868",
      brightRed: "#f7768e",
      brightGreen: "#9ece6a",
      brightYellow: "#e0af68",
      brightBlue: "#7aa2f7",
      brightMagenta: "#bb9af7",
      brightCyan: "#7dcfff",
      brightWhite: "#c0caf5",
    },
  },
  {
    id: "catppuccin-mocha",
    label: "Catppuccin Mocha",
    mode: "dark",
    swatch: ["#1e1e2e", "#89b4fa", "#a6e3a1", "#cba6f7"],
    vars: {
      "--color-bg": "#1e1e2e",
      "--color-bg-secondary": "#181825",
      "--color-bg-elevated": "#313244",
      "--color-bg-hover": "#313244",
      "--color-border": "#45475a",
      "--color-text": "#cdd6f4",
      "--color-text-secondary": "#bac2de",
      "--color-text-muted": "#6c7086",
      "--color-accent": "#89b4fa",
      "--color-accent-hover": "#b4befe",
      "--color-accent-soft": "#2a2f45",
      "--color-user-bubble": "#cdd6f4",
      "--color-user-bubble-text": "#1e1e2e",
      "--color-tool-bubble": "#313244",
      "--color-error": "#f38ba8",
      "--color-error-soft": "#3a2130",
      "--color-editor-bg": "#181825",
    },
    terminal: {
      background: "#1e1e2e",
      foreground: "#cdd6f4",
      cursor: "#f5e0dc",
      selectionBackground: "#585b70",
      black: "#45475a",
      red: "#f38ba8",
      green: "#a6e3a1",
      yellow: "#f9e2af",
      blue: "#89b4fa",
      magenta: "#f5c2e7",
      cyan: "#94e2d5",
      white: "#bac2de",
      brightBlack: "#585b70",
      brightRed: "#f38ba8",
      brightGreen: "#a6e3a1",
      brightYellow: "#f9e2af",
      brightBlue: "#89b4fa",
      brightMagenta: "#f5c2e7",
      brightCyan: "#94e2d5",
      brightWhite: "#a6adc8",
    },
  },
  {
    id: "dracula",
    label: "Dracula",
    mode: "dark",
    swatch: ["#282a36", "#bd93f9", "#50fa7b", "#ff79c6"],
    vars: {
      "--color-bg": "#282a36",
      "--color-bg-secondary": "#21222c",
      "--color-bg-elevated": "#343746",
      "--color-bg-hover": "#383a4a",
      "--color-border": "#44475a",
      "--color-text": "#f8f8f2",
      "--color-text-secondary": "#bfbfd9",
      "--color-text-muted": "#6272a4",
      "--color-accent": "#bd93f9",
      "--color-accent-hover": "#d6acff",
      "--color-accent-soft": "#392e52",
      "--color-user-bubble": "#f8f8f2",
      "--color-user-bubble-text": "#282a36",
      "--color-tool-bubble": "#343746",
      "--color-error": "#ff5555",
      "--color-error-soft": "#3d2430",
      "--color-editor-bg": "#21222c",
    },
    terminal: {
      background: "#282a36",
      foreground: "#f8f8f2",
      cursor: "#f8f8f2",
      selectionBackground: "#44475a",
      black: "#21222c",
      red: "#ff5555",
      green: "#50fa7b",
      yellow: "#f1fa8c",
      blue: "#bd93f9",
      magenta: "#ff79c6",
      cyan: "#8be9fd",
      white: "#f8f8f2",
      brightBlack: "#6272a4",
      brightRed: "#ff6e6e",
      brightGreen: "#69ff94",
      brightYellow: "#ffffa5",
      brightBlue: "#d6acff",
      brightMagenta: "#ff92df",
      brightCyan: "#a4ffff",
      brightWhite: "#ffffff",
    },
  },
  {
    id: "nord",
    label: "Nord",
    mode: "dark",
    swatch: ["#2e3440", "#88c0d0", "#a3be8c", "#81a1c1"],
    vars: {
      "--color-bg": "#2e3440",
      "--color-bg-secondary": "#3b4252",
      "--color-bg-elevated": "#434c5e",
      "--color-bg-hover": "#434c5e",
      "--color-border": "#4c566a",
      "--color-text": "#eceff4",
      "--color-text-secondary": "#d8dee9",
      "--color-text-muted": "#7b88a1",
      "--color-accent": "#88c0d0",
      "--color-accent-hover": "#8fbcbb",
      "--color-accent-soft": "#2f3d44",
      "--color-user-bubble": "#eceff4",
      "--color-user-bubble-text": "#2e3440",
      "--color-tool-bubble": "#3b4252",
      "--color-error": "#bf616a",
      "--color-error-soft": "#3d2b2e",
      "--color-editor-bg": "#3b4252",
    },
    terminal: {
      background: "#2e3440",
      foreground: "#d8dee9",
      cursor: "#d8dee9",
      selectionBackground: "#4c566a",
      black: "#3b4252",
      red: "#bf616a",
      green: "#a3be8c",
      yellow: "#ebcb8b",
      blue: "#81a1c1",
      magenta: "#b48ead",
      cyan: "#88c0d0",
      white: "#e5e9f0",
      brightBlack: "#4c566a",
      brightRed: "#bf616a",
      brightGreen: "#a3be8c",
      brightYellow: "#ebcb8b",
      brightBlue: "#81a1c1",
      brightMagenta: "#b48ead",
      brightCyan: "#8fbcbb",
      brightWhite: "#eceff4",
    },
  },
  {
    id: "gruvbox-dark",
    label: "Gruvbox Dark",
    mode: "dark",
    swatch: ["#282828", "#fe8019", "#b8bb26", "#fabd2f"],
    vars: {
      "--color-bg": "#282828",
      "--color-bg-secondary": "#1d2021",
      "--color-bg-elevated": "#3c3836",
      "--color-bg-hover": "#504945",
      "--color-border": "#504945",
      "--color-text": "#ebdbb2",
      "--color-text-secondary": "#d5c4a1",
      "--color-text-muted": "#a89984",
      "--color-accent": "#fe8019",
      "--color-accent-hover": "#fabd2f",
      "--color-accent-soft": "#3d2b1f",
      "--color-user-bubble": "#ebdbb2",
      "--color-user-bubble-text": "#282828",
      "--color-tool-bubble": "#3c3836",
      "--color-error": "#fb4934",
      "--color-error-soft": "#3c2626",
      "--color-editor-bg": "#1d2021",
    },
    terminal: {
      background: "#282828",
      foreground: "#ebdbb2",
      cursor: "#ebdbb2",
      selectionBackground: "#504945",
      black: "#282828",
      red: "#cc241d",
      green: "#98971a",
      yellow: "#d79921",
      blue: "#458588",
      magenta: "#b16286",
      cyan: "#689d6a",
      white: "#a89984",
      brightBlack: "#928374",
      brightRed: "#fb4934",
      brightGreen: "#b8bb26",
      brightYellow: "#fabd2f",
      brightBlue: "#83a598",
      brightMagenta: "#d3869b",
      brightCyan: "#8ec07c",
      brightWhite: "#ebdbb2",
    },
  },
  {
    id: "rose-pine",
    label: "Rosé Pine",
    mode: "dark",
    swatch: ["#191724", "#c4a7e7", "#9ccfd8", "#eb6f92"],
    vars: {
      "--color-bg": "#191724",
      "--color-bg-secondary": "#1f1d2e",
      "--color-bg-elevated": "#26233a",
      "--color-bg-hover": "#26233a",
      "--color-border": "#403d52",
      "--color-text": "#e0def4",
      "--color-text-secondary": "#908caa",
      "--color-text-muted": "#6e6a86",
      "--color-accent": "#c4a7e7",
      "--color-accent-hover": "#ebbcba",
      "--color-accent-soft": "#2d2a45",
      "--color-user-bubble": "#e0def4",
      "--color-user-bubble-text": "#191724",
      "--color-tool-bubble": "#1f1d2e",
      "--color-error": "#eb6f92",
      "--color-error-soft": "#332433",
      "--color-editor-bg": "#1f1d2e",
    },
    terminal: {
      background: "#191724",
      foreground: "#e0def4",
      cursor: "#e0def4",
      selectionBackground: "#403d52",
      black: "#26233a",
      red: "#eb6f92",
      green: "#31748f",
      yellow: "#f6c177",
      blue: "#9ccfd8",
      magenta: "#c4a7e7",
      cyan: "#ebbcba",
      white: "#e0def4",
      brightBlack: "#6e6a86",
      brightRed: "#eb6f92",
      brightGreen: "#31748f",
      brightYellow: "#f6c177",
      brightBlue: "#9ccfd8",
      brightMagenta: "#c4a7e7",
      brightCyan: "#ebbcba",
      brightWhite: "#e0def4",
    },
  },
  {
    id: "catppuccin-latte",
    label: "Catppuccin Latte",
    mode: "light",
    swatch: ["#eff1f5", "#1e66f5", "#40a02b", "#8839ef"],
    vars: {
      "--color-bg": "#eff1f5",
      "--color-bg-secondary": "#e6e9ef",
      "--color-bg-elevated": "#ffffff",
      "--color-bg-hover": "#ccd0da",
      "--color-border": "#ccd0da",
      "--color-text": "#4c4f69",
      "--color-text-secondary": "#5c5f77",
      "--color-text-muted": "#8c8fa1",
      "--color-accent": "#1e66f5",
      "--color-accent-hover": "#7287fd",
      "--color-accent-soft": "#dce0e8",
      "--color-user-bubble": "#4c4f69",
      "--color-user-bubble-text": "#eff1f5",
      "--color-tool-bubble": "#e6e9ef",
      "--color-error": "#d20f39",
      "--color-error-soft": "#f2dce1",
      "--color-editor-bg": "#ffffff",
    },
    terminal: {
      background: "#eff1f5",
      foreground: "#4c4f69",
      cursor: "#4c4f69",
      selectionBackground: "#acb0be",
      black: "#5c5f77",
      red: "#d20f39",
      green: "#40a02b",
      yellow: "#df8e1d",
      blue: "#1e66f5",
      magenta: "#ea76cb",
      cyan: "#179299",
      white: "#acb0be",
      brightBlack: "#6c6f85",
      brightRed: "#d20f39",
      brightGreen: "#40a02b",
      brightYellow: "#df8e1d",
      brightBlue: "#1e66f5",
      brightMagenta: "#ea76cb",
      brightCyan: "#179299",
      brightWhite: "#bcc0cc",
    },
  },
  {
    id: "gruvbox-light",
    label: "Gruvbox Light",
    mode: "light",
    swatch: ["#fbf1c7", "#af3a03", "#79740e", "#b57614"],
    vars: {
      "--color-bg": "#fbf1c7",
      "--color-bg-secondary": "#f2e5bc",
      "--color-bg-elevated": "#ffffff",
      "--color-bg-hover": "#ebdbb2",
      "--color-border": "#d5c4a1",
      "--color-text": "#3c3836",
      "--color-text-secondary": "#504945",
      "--color-text-muted": "#7c6f64",
      "--color-accent": "#af3a03",
      "--color-accent-hover": "#d65d0e",
      "--color-accent-soft": "#f2e0c9",
      "--color-user-bubble": "#3c3836",
      "--color-user-bubble-text": "#fbf1c7",
      "--color-tool-bubble": "#f2e5bc",
      "--color-error": "#9d0006",
      "--color-error-soft": "#f5dcd6",
      "--color-editor-bg": "#ffffff",
    },
    terminal: {
      background: "#fbf1c7",
      foreground: "#3c3836",
      cursor: "#3c3836",
      selectionBackground: "#d5c4a1",
      black: "#3c3836",
      red: "#cc241d",
      green: "#98971a",
      yellow: "#d79921",
      blue: "#458588",
      magenta: "#b16286",
      cyan: "#689d6a",
      white: "#7c6f64",
      brightBlack: "#928374",
      brightRed: "#9d0006",
      brightGreen: "#79740e",
      brightYellow: "#b57614",
      brightBlue: "#076678",
      brightMagenta: "#8f3f71",
      brightCyan: "#427b58",
      brightWhite: "#3c3836",
    },
  },
  {
    // Ethan Schoonover's original palette — base03/02/01/00/0/1/2/3 grayscale
    // ramp plus 8 fixed accent hues, identical across both modes (only which
    // base tones play bg vs fg swaps). Terminal ANSI mapping below is
    // Solarized's own canonical 16-color assignment (the same one its
    // official terminal.sh scripts ship), not an improvised one.
    id: "solarized-light",
    label: "Solarized Light",
    mode: "light",
    swatch: ["#fdf6e3", "#268bd2", "#859900", "#cb4b16"],
    vars: {
      "--color-bg": "#fdf6e3",
      "--color-bg-secondary": "#eee8d5",
      "--color-bg-elevated": "#fdf6e3",
      "--color-bg-hover": "#e6dfc9",
      "--color-border": "#d9d2b8",
      "--color-text": "#657b83",
      "--color-text-secondary": "#839496",
      "--color-text-muted": "#93a1a1",
      "--color-accent": "#268bd2",
      "--color-accent-hover": "#3f9fdb",
      "--color-accent-soft": "#dceefa",
      "--color-user-bubble": "#657b83",
      "--color-user-bubble-text": "#fdf6e3",
      "--color-tool-bubble": "#eee8d5",
      "--color-error": "#dc322f",
      "--color-error-soft": "#f8dedd",
      "--color-editor-bg": "#ffffff",
    },
    terminal: {
      background: "#fdf6e3",
      foreground: "#657b83",
      cursor: "#657b83",
      selectionBackground: "#eee8d5",
      black: "#073642",
      red: "#dc322f",
      green: "#859900",
      yellow: "#b58900",
      blue: "#268bd2",
      magenta: "#d33682",
      cyan: "#2aa198",
      white: "#eee8d5",
      brightBlack: "#002b36",
      brightRed: "#cb4b16",
      brightGreen: "#586e75",
      brightYellow: "#657b83",
      brightBlue: "#839496",
      brightMagenta: "#6c71c4",
      brightCyan: "#93a1a1",
      brightWhite: "#fdf6e3",
    },
  },
  {
    id: "one-light",
    label: "One Light",
    mode: "light",
    swatch: ["#fafafa", "#4078f2", "#50a14f", "#a626a4"],
    vars: {
      "--color-bg": "#fafafa",
      "--color-bg-secondary": "#f0f0f1",
      "--color-bg-elevated": "#fafafa",
      "--color-bg-hover": "#e8e8ea",
      "--color-border": "#e5e5e6",
      "--color-text": "#383a42",
      "--color-text-secondary": "#696c77",
      "--color-text-muted": "#a0a1a7",
      "--color-accent": "#4078f2",
      "--color-accent-hover": "#5a8ff7",
      "--color-accent-soft": "#e4ecfd",
      "--color-user-bubble": "#383a42",
      "--color-user-bubble-text": "#fafafa",
      "--color-tool-bubble": "#f0f0f1",
      "--color-error": "#e45649",
      "--color-error-soft": "#fbe4e2",
      "--color-editor-bg": "#fafafa",
    },
    terminal: {
      background: "#fafafa",
      foreground: "#383a42",
      cursor: "#383a42",
      selectionBackground: "#e5e5e6",
      black: "#383a42",
      red: "#e45649",
      green: "#50a14f",
      yellow: "#c18401",
      blue: "#4078f2",
      magenta: "#a626a4",
      cyan: "#0184bc",
      white: "#a0a1a7",
      brightBlack: "#696c77",
      brightRed: "#e45649",
      brightGreen: "#50a14f",
      brightYellow: "#c18401",
      brightBlue: "#4078f2",
      brightMagenta: "#a626a4",
      brightCyan: "#0184bc",
      brightWhite: "#383a42",
    },
  },
  {
    // Real palette values (bg0/fg/grey0-2 + the 7 accents) confirmed against
    // sainnhe/everforest's own published palette.md, medium-contrast light
    // variant — not guessed. Accent is green, Everforest's own signature
    // hue, not blue/orange like most of this file's other themes.
    id: "everforest-light",
    label: "Everforest Light",
    mode: "light",
    swatch: ["#fdf6e3", "#8da101", "#3a94c5", "#f57d26"],
    vars: {
      "--color-bg": "#fdf6e3",
      "--color-bg-secondary": "#f4f0d9",
      "--color-bg-elevated": "#fdf6e3",
      "--color-bg-hover": "#efebd4",
      "--color-border": "#e6e2cc",
      "--color-text": "#5c6a72",
      "--color-text-secondary": "#829181",
      "--color-text-muted": "#a6b0a0",
      "--color-accent": "#8da101",
      "--color-accent-hover": "#9db015",
      "--color-accent-soft": "#e8edc8",
      "--color-user-bubble": "#5c6a72",
      "--color-user-bubble-text": "#fdf6e3",
      "--color-tool-bubble": "#f4f0d9",
      "--color-error": "#f85552",
      "--color-error-soft": "#fbdedd",
      "--color-editor-bg": "#ffffff",
    },
    terminal: {
      background: "#fdf6e3",
      foreground: "#5c6a72",
      cursor: "#5c6a72",
      selectionBackground: "#e6e2cc",
      black: "#5c6a72",
      red: "#f85552",
      green: "#8da101",
      yellow: "#dfa000",
      blue: "#3a94c5",
      magenta: "#df69ba",
      cyan: "#35a77c",
      white: "#a6b0a0",
      brightBlack: "#829181",
      brightRed: "#f85552",
      brightGreen: "#8da101",
      brightYellow: "#dfa000",
      brightBlue: "#3a94c5",
      brightMagenta: "#df69ba",
      brightCyan: "#35a77c",
      brightWhite: "#5c6a72",
    },
  },
  {
    // GitHub's own default light UI (primer/primitives design tokens).
    id: "github-light",
    label: "GitHub Light",
    mode: "light",
    swatch: ["#ffffff", "#0969da", "#1a7f37", "#8250df"],
    vars: {
      "--color-bg": "#ffffff",
      "--color-bg-secondary": "#f6f8fa",
      "--color-bg-elevated": "#ffffff",
      "--color-bg-hover": "#eaeef2",
      "--color-border": "#d0d7de",
      "--color-text": "#1f2328",
      "--color-text-secondary": "#656d76",
      "--color-text-muted": "#8c959f",
      "--color-accent": "#0969da",
      "--color-accent-hover": "#0757ba",
      "--color-accent-soft": "#ddf4ff",
      "--color-user-bubble": "#1f2328",
      "--color-user-bubble-text": "#ffffff",
      "--color-tool-bubble": "#f6f8fa",
      "--color-error": "#cf222e",
      "--color-error-soft": "#ffebe9",
      "--color-editor-bg": "#ffffff",
    },
    terminal: {
      background: "#ffffff",
      foreground: "#1f2328",
      cursor: "#1f2328",
      selectionBackground: "#d0d7de",
      black: "#1f2328",
      red: "#cf222e",
      green: "#1a7f37",
      yellow: "#9a6700",
      blue: "#0969da",
      magenta: "#8250df",
      cyan: "#1b7c83",
      white: "#8c959f",
      brightBlack: "#656d76",
      brightRed: "#cf222e",
      brightGreen: "#1a7f37",
      brightYellow: "#9a6700",
      brightBlue: "#0969da",
      brightMagenta: "#8250df",
      brightCyan: "#1b7c83",
      brightWhite: "#1f2328",
    },
  },
  {
    // Sublime Text's classic — arguably THE most recognized dark theme.
    // Monokai's own source material doesn't really have a second, distinct
    // "true red" separate from its signature hot pink, so accent/error are
    // deliberately split across its two other iconic hues (orange for
    // accent, pink for error/red) rather than reusing one color for both UI
    // roles. Terminal ANSI mapping below is the real, widely-ported
    // Monokai terminal.sh/iTerm2 16-color scheme, not improvised.
    id: "monokai",
    label: "Monokai",
    mode: "dark",
    swatch: ["#272822", "#fd971f", "#a6e22e", "#66d9ef"],
    vars: {
      "--color-bg": "#272822",
      "--color-bg-secondary": "#1e1f1c",
      "--color-bg-elevated": "#2d2e27",
      "--color-bg-hover": "#3e3d32",
      "--color-border": "#49483e",
      "--color-text": "#f8f8f2",
      "--color-text-secondary": "#cfcfc2",
      "--color-text-muted": "#75715e",
      "--color-accent": "#fd971f",
      "--color-accent-hover": "#ffb454",
      "--color-accent-soft": "#3d2f18",
      "--color-user-bubble": "#f8f8f2",
      "--color-user-bubble-text": "#272822",
      "--color-tool-bubble": "#2d2e27",
      "--color-error": "#f92672",
      "--color-error-soft": "#3a1f2b",
      "--color-editor-bg": "#1e1f1c",
    },
    terminal: {
      background: "#272822",
      foreground: "#f8f8f2",
      cursor: "#f8f8f2",
      selectionBackground: "#49483e",
      black: "#272822",
      red: "#f92672",
      green: "#a6e22e",
      yellow: "#e6db74",
      blue: "#66d9ef",
      magenta: "#ae81ff",
      cyan: "#a1efe4",
      white: "#f8f8f2",
      brightBlack: "#75715e",
      brightRed: "#f92672",
      brightGreen: "#a6e22e",
      brightYellow: "#f4bf75",
      brightBlue: "#66d9ef",
      brightMagenta: "#ae81ff",
      brightCyan: "#a1efe4",
      brightWhite: "#f9f8f5",
    },
  },
  {
    // Atom's theme — still one of the most-installed VS Code themes ever.
    // Pairs with one-light above the same way metaharn-dark/light and the
    // Catppuccin/Gruvbox pairs already do.
    id: "one-dark",
    label: "One Dark",
    mode: "dark",
    swatch: ["#282c34", "#61afef", "#98c379", "#c678dd"],
    vars: {
      "--color-bg": "#282c34",
      "--color-bg-secondary": "#21252b",
      "--color-bg-elevated": "#2c313a",
      "--color-bg-hover": "#2c313c",
      "--color-border": "#3e4451",
      "--color-text": "#abb2bf",
      "--color-text-secondary": "#9198a1",
      "--color-text-muted": "#5c6370",
      "--color-accent": "#61afef",
      "--color-accent-hover": "#7ec0ff",
      "--color-accent-soft": "#1d2b3a",
      "--color-user-bubble": "#abb2bf",
      "--color-user-bubble-text": "#282c34",
      "--color-tool-bubble": "#2c313a",
      "--color-error": "#e06c75",
      "--color-error-soft": "#3a2529",
      "--color-editor-bg": "#21252b",
    },
    terminal: {
      background: "#282c34",
      foreground: "#abb2bf",
      cursor: "#528bff",
      selectionBackground: "#3e4451",
      black: "#282c34",
      red: "#e06c75",
      green: "#98c379",
      yellow: "#e5c07b",
      blue: "#61afef",
      magenta: "#c678dd",
      cyan: "#56b6c2",
      white: "#abb2bf",
      brightBlack: "#5c6370",
      brightRed: "#e06c75",
      brightGreen: "#98c379",
      brightYellow: "#e5c07b",
      brightBlue: "#61afef",
      brightMagenta: "#c678dd",
      brightCyan: "#56b6c2",
      brightWhite: "#ffffff",
    },
  },
  {
    // Same shared Ethan Schoonover palette as solarized-light — base03/02/
    // 01/00/0/1/2/3 grayscale ramp plus the identical 8 accent hues, just
    // the dark-mode assignment (base0 for body text, per Solarized's own
    // convention — base00 is the light-mode text tone instead). Terminal
    // ANSI mapping is Solarized's real canonical dark 16-color scheme.
    // Primary text sits just at ~4.9:1 against bg — a known, deliberate,
    // inherent property of Solarized's real palette (its light sibling has
    // the same characteristic), not adjusted away from the authentic values.
    id: "solarized-dark",
    label: "Solarized Dark",
    mode: "dark",
    swatch: ["#002b36", "#268bd2", "#859900", "#cb4b16"],
    vars: {
      "--color-bg": "#002b36",
      "--color-bg-secondary": "#073642",
      "--color-bg-elevated": "#002b36",
      "--color-bg-hover": "#0a4552",
      "--color-border": "#0d4f5c",
      "--color-text": "#839496",
      "--color-text-secondary": "#93a1a1",
      "--color-text-muted": "#586e75",
      "--color-accent": "#268bd2",
      "--color-accent-hover": "#3f9fdb",
      "--color-accent-soft": "#0c3947",
      "--color-user-bubble": "#839496",
      "--color-user-bubble-text": "#002b36",
      "--color-tool-bubble": "#073642",
      "--color-error": "#dc322f",
      "--color-error-soft": "#3b1f1e",
      "--color-editor-bg": "#073642",
    },
    terminal: {
      background: "#002b36",
      foreground: "#839496",
      cursor: "#839496",
      selectionBackground: "#073642",
      black: "#073642",
      red: "#dc322f",
      green: "#859900",
      yellow: "#b58900",
      blue: "#268bd2",
      magenta: "#d33682",
      cyan: "#2aa198",
      white: "#eee8d5",
      brightBlack: "#002b36",
      brightRed: "#cb4b16",
      brightGreen: "#586e75",
      brightYellow: "#657b83",
      brightBlue: "#839496",
      brightMagenta: "#6c71c4",
      brightCyan: "#93a1a1",
      brightWhite: "#fdf6e3",
    },
  },
  {
    // Sarah Drasner's widely-loved VS Code theme — distinct deep-navy/blue
    // identity not otherwise represented in this file. Real published
    // values (its own official theme source), terminal mapping likewise.
    id: "night-owl",
    label: "Night Owl",
    mode: "dark",
    swatch: ["#011627", "#82aaff", "#22da6e", "#c792ea"],
    vars: {
      "--color-bg": "#011627",
      "--color-bg-secondary": "#010e1a",
      "--color-bg-elevated": "#0b2942",
      "--color-bg-hover": "#1d3b53",
      "--color-border": "#1d3b53",
      "--color-text": "#d6deeb",
      "--color-text-secondary": "#a1aab8",
      "--color-text-muted": "#637777",
      "--color-accent": "#82aaff",
      "--color-accent-hover": "#a1c4ff",
      "--color-accent-soft": "#1d3049",
      "--color-user-bubble": "#d6deeb",
      "--color-user-bubble-text": "#011627",
      "--color-tool-bubble": "#0b2942",
      "--color-error": "#ef5350",
      "--color-error-soft": "#3a1f21",
      "--color-editor-bg": "#010e1a",
    },
    terminal: {
      background: "#011627",
      foreground: "#d6deeb",
      cursor: "#80a4c2",
      selectionBackground: "#1d3b53",
      black: "#011627",
      red: "#ef5350",
      green: "#22da6e",
      yellow: "#addb67",
      blue: "#82aaff",
      magenta: "#c792ea",
      cyan: "#21c7a8",
      white: "#d6deeb",
      brightBlack: "#575656",
      brightRed: "#ef5350",
      brightGreen: "#22da6e",
      brightYellow: "#ffeb95",
      brightBlue: "#82aaff",
      brightMagenta: "#c792ea",
      brightCyan: "#7fdbca",
      brightWhite: "#ffffff",
    },
  },
];

export const DEFAULT_DARK_THEME_ID = "tokyo-night-storm";
export const DEFAULT_LIGHT_THEME_ID = "catppuccin-latte";

export function getTheme(id: string): ThemeDef | undefined {
  return THEMES.find((t) => t.id === id);
}
